### ISSUE TITLE
[ISSUE] SharePriceIncrease

### ISSUE THREAD

**Issue by e-delaney** [time-series-machine-learning/tsml-repo#89]
**Which dataset/datasets have you an issue with?**

SharePriceIncrease

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)? **

I got it from timeseriesclassification.com.

**Whats the issue?**

The data does not load due to the fact that it is incorrectly formatted. On inspection of the data it appears that the metadata also describes other datasets in the archive (possible copy/paste error - see screenshot) which is the root cause of the issue. 

When I remove these lines and save the data the issue is solved, and the data can be loaded using sktime functionality. I attach an image of the code issue using sktime loader and also the data on inspection. 

Also thanks for the repo. 

![error_notebook](https://user-images.githubusercontent.com/55100385/215090777-c7743046-6727-4359-91c6-ebaa17f55470.PNG)
![error_ts_data](https://user-images.githubusercontent.com/55100385/215090780-41f14b78-1504-4ceb-8d67-62b60f9d4131.PNG)

**Comment by TonyBagnall** [comment]
thanks for that, I'll upload the correct version

**Comment by TonyBagnall** [comment]
sorry this took so long! Fixed now, you can load with this

```python
from aeon.datasets import load_classification
X, y, meta = load_classification("SharePriceIncrease")
print(meta)
```
