### ISSUE TITLE
[ISSUE] MotionSensorHAR download link is not working

### ISSUE THREAD

**Issue by ucarseyhan** [time-series-machine-learning/tsml-repo#91]
I am trying to download the MotionSensorHAR from the following link

https://www.timeseriesclassification.com/description.php?Dataset=MotionSenseHAR

However, the link does not work for me. I did not see the dataset in the TSC/TSCL downloadable dataset. Could you please help me? Thank you very much.

**Comment by TonyBagnall** [comment]
sorry about that, should be fixed now
