### ISSUE TITLE
CharacterTrajectories data set has been updated [ISSUE]

### ISSUE THREAD

**Issue by philipdarke** [time-series-machine-learning/tsml-repo#95]
**Which dataset/datasets have you an issue with?**

The `CharacterTrajectories_TRAIN.ts` and `CharacterTrajectories_TEST.ts` files in the CharacterTrajectories data set appear to have changed on 1 November 2023. They now include initial and trailing zeros (previously these had been removed?) and the training and test split appears to have been resampled (the sum of the training/test data are -39307.1016/-42578.5156 compared to -41497.0039/-40388.6055 previously).

I think the data are now more consistent with the UCI version ([link](https://archive.ics.uci.edu/dataset/175/character+trajectories)) which, from memory, include initial/trailing zeros.

The data in the multivariate [download](http://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip) are the old version.

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**

Downloaded from timeseriesclassification.com [link](https://www.timeseriesclassification.com/aeon-toolkit/CharacterTrajectories.zip).

**Whats the issue?**

This potentially prevents reproducibility of results depending on any downstream data processing in place.

Is there a rationale for the change?

Would you consider versioning data or, if not, flagging any data changes on the website and in a README in the `.zip` download?

Thanks again for your work on providing this resource, it's really appreciated.

**Comment by philipdarke** [comment]
Apologies @TonyBagnall, I've just seen issue #92 and aeon-toolkit/aeon#853 which explain the rationale.

Is there an argument for removing the padding as previously and accepting a missing/zero value in the inconsistent channel? It would avoid the big data change and new train/test split.

**Comment by TonyBagnall** [comment]
hi @philipdarke as you see, the problem was that the removal of padding (done by a PhD student five years ago) resulted in unequal length series within a single case, and we do not support that format at aeon. This was a problem with a fair number of cases, not just one. I have no record of how the padding was removed back then, soh I took the decision to revert to the exact same form as the UCI, as this seemed the most transparent solution. Sorry if its caused you problems

**Comment by philipdarke** [comment]
Thanks for the quick reply @TonyBagnall.

Reverting to UCI data is pragmatic but most(?) users will want to remove the padding and face the same problem - so I'll try and win you around one last time!

There are 39 cases where channel x or y is shorter after removing the padding. They have a greater number of trailing zeros and a final observation in the range 1e-12 to 1e-14. The data was differentiated so this likely corresponds to a broadly stationary pen after drawing the character. I suspect the smoothing applied before differentiation resulted in zero values at the end of the sequence (or values so small there was numeric underflow). These were mistakenly assumed to be padding and removed.

Some users drop these 39 cases. I propose the shorter channel should be padded with trailing zeros to the length of the other channels.

The revised data would comply with the aeon `.ts` specification, be closer in spirit to the previous version of the data, and maintain the same train and test split. So I think it's a better compromise than reverting to UCI - but just a suggestion.

I can provide code and updated data files if you want to look at this further. This would solve the audit trail problem.

**Comment by TonyBagnall** [comment]
I'm fine with that, I prefer unpadded too. Thanks for taking the time to sort it. Updating the read me is a very good idea. If you send it to us tony@timeseriesclassification.com, I'll update the website and repo.

**Comment by philipdarke** [comment]
I have forwarded unpadded `.ts` files with the same training/test splits as historically used in the TSC repository, the fix above for the 39 cases with unequal channel lengths, and the same numeric precision as the original UCI data. The code is at https://github.com/philipdarke/chartrajs-data.

**Comment by TonyBagnall** [comment]
great, so its all there 
https://timeseriesclassification.com/description.php?Dataset=CharacterTrajectories
and this all works
```python
from aeon.datasets._data_loaders import download_dataset
download_dataset("CharacterTrajectories", save_path="C:\Temp")

import numpy as np
from aeon.datasets import load_classification
X, y, meta_data = load_classification("CharacterTrajectories", split="TRAIN")
testX, testy, meta_data = load_classification("CharacterTrajectories", split="TEST")
print(" Type of X = ", type(X))
print(" Shape of X = ", len(X))
print(" Meta data = ", meta_data)
from aeon.classification import DummyClassifier
fp = DummyClassifier()
fp.fit(X,y)
pred = fp.predict(testX)
print("Number correct = ",np.sum(pred==testy))
print("Accuracy = ",np.sum(pred==testy)/len(testy))
```
Thanks for sorting this out @philipdarke. I have updated the readme on this repo. Think we can close this issue?

**Comment by philipdarke** [comment]
Looks good @TonyBagnall, thanks again for the quick response. Happy to close this off.
